name: windows-build

on:
  push:
    branches:
      - dev
      - main
    paths-ignore: [".ci_helpers/docker/**", "**/docker.yaml"]
  pull_request:
  workflow_dispatch:

env:
  CONDA_ENV: echopype
  NUM_WORKERS: 2

jobs:
  windows-test:
      name: windows-${{ matrix.python-version }}-build
      runs-on: "windows-latest"
      if: github.repository == 'OSOceanAcoustics/echopype'
      continue-on-error: ${{ matrix.experimental }}
      strategy:
        fail-fast: false
        matrix:
          include:
          - python-version: 3.9
            experimental: false
      defaults:
        run:
          shell: powershell
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Fetch all history for all branches and tags.
        - name: Retrieve test data
          uses: ./.github/actions/gdrive-rclone
          env:
            GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
            ROOT_FOLDER_ID: ${{ secrets.TEST_DATA_FOLDER_ID }}
        - name: Setup micromamba
          uses: mamba-org/provision-with-micromamba@v15
          with:
            environment-file: .ci_helpers/py${{ matrix.python-version }}.yaml
            environment-name: ${{ env.CONDA_ENV }}
            cache-env: true
            cache-env-key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(format('.ci_helpers/py{0}.yaml', matrix.python-version)) }}
        - name: Print conda env
          run: |
            micromamba info
            micromamba env list
            micromamba list
        - name: Install echopype
          run: |
            python -m pip install -e ".[plot]"
        - name: Run convert test
          run: |
            pytest -vvv echopype/tests/convert/test_convert_source_target_locs.py::test_convert_ek
